#!/usr/bin/env bash

# license: GPL 3


# Dit script configureert Linux Mint Cinnamon voor DJOG. 
# Stelt automatische veiligheidsupdates in.
# Voegt gebruiker toe aan dialout group, voor Arduino. Maakt een nieuwe gebruiker 'djog' aan. Voegt die ook toe aan dialout.
# Zet de helderheid van het beeldscherm wat naar beneden voor langere batterijduur.
# Configureert de batterij applet in het paneel zodanig dat het percentage en duur batterij toont.


base_dir="linux-mint-cinnamon-djog"
data_dir="$base_dir/data"



continue_function() {
	read -r answer
	case "$answer" in
		j )      
			:	
			;;
		n ) 		
			exit 0
			;;
		*)  					
			exit 1  
	esac
}


printf "%s\n" "Dit script configureert Linux Mint Cinnamon voor DJOG. Doorgaan? (j/n)"

continue_function


# Stel automatische veiligheidsupdates in.

if ! command -v "unattended-upgrades" >/dev/null; then
	sudo apt update && sudo apt install unattended-upgrades -y || exit 1
fi

sudo dpkg-reconfigure --priority=low unattended-upgrades || exit 1

# Scherm helderheid verminderen voor minder batterijconsumptie.

if [[ -e "/sys/class/backlight/intel_backlight/max_brightness" ]]; then
	sudo cp "/sys/class/backlight/intel_backlight/brightness" "/sys/class/backlight/intel_backlight/brightness"_bak || exit 1  # FIXME: kan geen backup maken, niet de juiste rechten als root?! 
	read -r max_brightness < "/sys/class/backlight/intel_backlight/max_brightness" || exit 1
	reduced_brightness=$((max_brightness * 80 / 100 )) || exit 1
	echo "$reduced_brightness" | sudo tee /sys/class/backlight/intel_backlight/brightness || exit 1
else
	printf "%s\n" "Kan bestand voor instellen schermhelderheid (intel) niet vinden, we slaan dit over."
fi


# Check of current user (admin?) is in dialout group. If not add them.
if ! getent group dialout >/dev/null; then
	sudo usermod -a -G dialout "$USER" || exit 1
fi


#Add normal user djog, without root access. Give it password 'djog'.

sudo adduser djo

# Add djog to dialout group for Arduino.

sudo usermod -a -G dialout djo


#[[ "$XDG_CURRENT_DESKTOP" != "X-Cinnamon" ]] && { printf "%s\n" "Waarschuwing: Desktopomgeving Cinnamon niet gedetecteerd. Batterij applet setup slaan we over." >&2; exit 1; }


# Backup originele file.

cinnamon_applet_dir="/usr/share/cinnamon/applets/power@cinnamon.org"
target_file="settings-schema.json"
sudo cp "$cinnamon_applet_dir/$target_file" "$cinnamon_applet_dir/$target_file"_bak || exit 1
sudo cp "$data_dir/power@cinnamon.org.json" "$cinnamon_applet_dir/$target_file" || exit 1


exit 0
