#!/usr/bin/env bash

# Audio, spelletjes-junior, ... , worden niet standaard geinstalleerd.

sudo apt update && sudo apt upgrade -y &&\
#sudo apt install ./metapackages-ubuntu-djog/djog-ubuntu-audio*.deb -y &&\
#sudo apt install ./metapackages-ubuntu-djog/djog-ubuntu-spelletjes-junior*.deb -y &&\
sudo apt install ./metapackages-ubuntu-djog/djog-ubuntu-admin*.deb -y &&\
sudo apt install ./metapackages-ubuntu-djog/djog-ubuntu-desktop*.deb -y &&\
sudo apt install ./metapackages-ubuntu-djog/djog-ubuntu-multimedia*.deb -y &&\
sudo apt install ./metapackages-ubuntu-djog/djog-ubuntu-programmeren*.deb -y &&\
sudo apt install ./metapackages-ubuntu-djog/djog-ubuntu-spelletjes_*.deb -y 

exit 0


