#!/usr/bin/env bash

# GPL3+

# Simpel script. Print geheugensteuntjes voor kinderen voor simpel gebruik van git en de terminal.

target="${1?argument ontbreekt, waar wil je hulp mee? (djo-help -h)}"

git_hints=("git add ." "git commit -am \"mijn commit\"" "git push")
term_hints=("ls" "cd /home/djo" "cd ~/" "cd" "<TAB>" "copy/paste: ctr+shift+c ctr+shift+v" "copy/paste: selecteren/middelste muisknop" "trash test.txt" "man ls" )


show_help() {
	options_array=("-h -? --help" "-g --git" "-t --term --terminal")

	printf "%s\n" "Opties:"
	printf "%s\n" "${options_array[@]}"

}


while :; do
    case $1 in
        -h|-\?|--help)
            show_help    # Display a usage synopsis.
            exit
            ;;
		-g|--git)
			target="git"
            break
            ;;
		-t|--terminal|--term)
			target="term"
            break
            ;;
        ?*)
            printf 'Waarschuwing: onbekende optie %s\n' "$1" >&2
            ;;
        *)               # Default case: No more options, so break out of the loop.
            break
    esac

    shift
done


if [[ "$target" = "git" ]]; then
	printf '%s\n' "${git_hints[@]}"
elif [[ "$target" = "term" ]]; then
	printf '%s\n' "${term_hints[@]}"
fi
